### ISSUE TITLE
issue of feed watchdog

### ISSUE THREAD

**Issue by tematou** [No-Chicken/OV-Watch#6]
hi, The watchdog task should monitor each task, Not feeding the dog in the watchdog task.

**Comment by No-Chicken** [comment]
thx for your feedback, watchdog just feeding in the watchdog task is all right, no need in other tasks, because once the cpu chocked in any task, any task include watchdog task will not running, then system will be reset

**Comment by tematou** [comment]
All right



---- Replied Message ----
| From | Kingham ***@***.***> |
| Date | 07/26/2024 17:53 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [No-Chicken/OV-Watch] issue of feed watchdog (Issue #6) |

thx for your feedback, watchdog just feeding in the watchdog task is all right, no need in other tasks, because once the cpu chocked in any task, any task include watchdog task will not running, then system will be reset

**Comment by tematou** [comment]
If a task does not work, but watchdog task is running ,Will the system reboot?
